name: Test

on:
  workflow_dispatch:
  push:
    branches:
      - aws-project

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: 'aws-project'
                
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install -r app/requirements_flask.txt

      - name: Run tests
        run: pytest tests
